### ISSUE TITLE
Add scheduled backups to CNPG

### ISSUE THREAD

**Issue by nvernooy** [getscaf/scaf#99]
**AC:**
* Update the cloud native PG cluster manifest with a backup configuration that sets up a backup to AWS S3 bucket as per the example below
* Add AWS `ACCESS_KEY_ID` and `ACCESS_SECRET_KEY` to k8s/templates/secrets.yaml.template
* Update the Makefile to source `ACCESS_KEY_ID` and `ACCESS_SECRET_KEY` from 1password when generating the secrets

```
  ...
  backup:
    barmanObjectStore:
      destinationPath: S3_BACKUP_KUSTOMIZED
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
      wal:
          compression: gzip
      data:
          compression: gzip
          jobs: 1
      tags:
        backupRetentionPolicy: "expire"
      historyTags:
        backupRetentionPolicy: "keep"
    retentionPolicy: "30d"

  primaryUpdateStrategy: unsupervised

  storage:
    size: 10Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: scheduled-backup
spec:
  schedule: "1 0 0 * * 0"
  suspend: false
  immediate: true
  backupOwnerReference: self
  cluster:
    name: db
```

**Tech notes**
For info see [documentation](https://cloudnative-pg.io/documentation/1.22/backup_barmanobjectstore/#common-object-stores)

**Comment by nvernooy** [comment]
Prod backups should be performed daily

`{{cookiecutter.project_slug}}/k8s/prod/kustomization.yaml`

```
- patch: |-
    - op: replace
      path: /spec/schedule
      value: "1 0 0 * * *"
  target:
    kind: ScheduledBackup
    name: scheduled-backup
```
